#############################################################################
# Makefile for building: 4Stones.app/Contents/MacOS/4Stones
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  4Stones.pro
# Template: app
# Command: /Users/aarondancer/Applications/Qt/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 4Stones.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang -I. -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/aarondancer/Applications/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/aarondancer/Applications/Qt/5.3/clang_64/lib -L/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/../qml/QtQuick.2/ -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/aarondancer/Applications/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		grid.cpp \
		player.cpp \
		ai.cpp \
		global.cpp qrc_qml.cpp \
		moc_grid.cpp \
		moc_player.cpp
OBJECTS       = main.o \
		grid.o \
		player.o \
		ai.o \
		global.o \
		qrc_qml.o \
		moc_grid.o \
		moc_player.o
DIST          = /Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/c++11.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/declarative_debug.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		4Stones.pro main.cpp \
		grid.cpp \
		player.cpp \
		ai.cpp \
		global.cpp
QMAKE_TARGET  = 4Stones
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = 4Stones.app/Contents/MacOS/4Stones

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile 4Stones.app/Contents/PkgInfo 4Stones.app/Contents/Resources/empty.lproj 4Stones.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d 4Stones.app/Contents/MacOS/ || mkdir -p 4Stones.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 4Stones.pro /Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/c++11.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/declarative_debug.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		4Stones.pro \
		qml.qrc \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 4Stones.pro
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qdevice.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/device_config.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/unix.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/mac.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/macx.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/qconfig.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/default_post.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/c++11.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qml_debug.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/declarative_debug.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/qt.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/resources.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/moc.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/yacc.prf:
/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/features/lex.prf:
4Stones.pro:
qml.qrc:
/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 4Stones.pro

qmake_all: FORCE

4Stones.app/Contents/PkgInfo: 
	@test -d 4Stones.app/Contents || mkdir -p 4Stones.app/Contents
	@$(DEL_FILE) 4Stones.app/Contents/PkgInfo
	@echo "APPL????" >4Stones.app/Contents/PkgInfo
4Stones.app/Contents/Resources/empty.lproj: 
	@test -d 4Stones.app/Contents/Resources || mkdir -p 4Stones.app/Contents/Resources
	@touch 4Stones.app/Contents/Resources/empty.lproj
	
4Stones.app/Contents/Info.plist: 
	@test -d 4Stones.app/Contents || mkdir -p 4Stones.app/Contents
	@$(DEL_FILE) 4Stones.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,sevenpm.4Stones,g" -e "s,@EXECUTABLE@,4Stones,g" -e "s,@TYPEINFO@,????,g" /Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >4Stones.app/Contents/Info.plist
dist: 
	@test -d .tmp/4Stones1.0.0 || mkdir -p .tmp/4Stones1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/4Stones1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/4Stones1.0.0/ && $(COPY_FILE) --parents grid.h player.h ai.h global.h .tmp/4Stones1.0.0/ && $(COPY_FILE) --parents main.cpp grid.cpp player.cpp ai.cpp global.cpp .tmp/4Stones1.0.0/ && (cd `dirname .tmp/4Stones1.0.0` && $(TAR) 4Stones1.0.0.tar 4Stones1.0.0 && $(COMPRESS) 4Stones1.0.0.tar) && $(MOVE) `dirname .tmp/4Stones1.0.0`/4Stones1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/4Stones1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r 4Stones.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		MainMenu.qml \
		kite.jpg \
		ripples.png \
		forest.jpg \
		4Stones.png \
		Login.qml \
		main.qml
	/Users/aarondancer/Applications/Qt/5.3/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_grid.cpp moc_player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_grid.cpp moc_player.cpp
moc_grid.cpp: /Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		grid.h
	/Users/aarondancer/Applications/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang -I'/Users/aarondancer/Dropbox/UHD/Intro to Software Engineering/4Stones/4Stones' -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/aarondancer/Applications/Qt/5.3/clang_64/lib grid.h -o moc_grid.cpp

moc_player.cpp: /Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		global.h \
		grid.h \
		player.h \
		ai.h \
		player.h
	/Users/aarondancer/Applications/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/aarondancer/Applications/Qt/5.3/clang_64/mkspecs/macx-clang -I'/Users/aarondancer/Dropbox/UHD/Intro to Software Engineering/4Stones/4Stones' -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/aarondancer/Applications/Qt/5.3/clang_64/lib player.h -o moc_player.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QGuiApplication \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlApplicationEngine \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlapplicationengine.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QtQml \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qtqmlglobal.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmldebug.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qjsengine.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qjsvalue.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qjsvalueiterator.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqml.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlabstracturlinterceptor.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlcomponent.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlcontext.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlengine.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlerror.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlexpression.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlextensioninterface.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlextensionplugin.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlfile.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlfileselector.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlincubator.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlinfo.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlnetworkaccessmanagerfactory.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlparserstatus.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlprivate.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlproperty.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlpropertyvaluesource.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlscriptstring.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlpropertymap.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qtqmlversion.h \
		ai.h \
		player.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		global.h \
		grid.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/QQuickView \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

grid.o: grid.cpp grid.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid.cpp

player.o: player.cpp player.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		global.h \
		grid.h \
		ai.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

ai.o: ai.cpp ai.h \
		player.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		global.h \
		grid.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ai.o ai.cpp

global.o: global.cpp global.h \
		grid.h \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Users/aarondancer/Applications/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		player.h \
		ai.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o global.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_grid.o: moc_grid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grid.o moc_grid.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/4Stones/bin || mkdir -p $(INSTALL_ROOT)/opt/4Stones/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/4Stones/bin/4Stones.app"
	
	-$(INSTALL_DIR) "4Stones.app" "$(INSTALL_ROOT)/opt/4Stones/bin/4Stones.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/4Stones/bin/4Stones.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/4Stones/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

